name: Download Unsplash Image

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Optional: Automatically trigger the workflow every day at midnight

jobs:
  download_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install required Python libraries
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download image from Unsplash
      run: |
        python3 - <<EOF
import requests
import os

# Direct image URL from Unsplash
image_url = "https://plus.unsplash.com/premium_photo-1736798695947-2c7661f72bc8?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

# Create a folder to save the image (if not exists)
os.makedirs("downloaded_images", exist_ok=True)

# Get the image content
response = requests.get(image_url)

# Check if the request was successful
if response.status_code == 200:
    # Extract the image filename from the URL (optional: customize if necessary)
    image_filename = image_url.split("/")[-1].split("?")[0]

    # Save the image in the 'downloaded_images' folder
    with open(f"downloaded_images/{image_filename}", "wb") as file:
        file.write(response.content)
    print(f"Image successfully downloaded: {image_filename}")
else:
    print("Failed to download the image")

EOF
