name: Random GitHub Action Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List directory contents (Debug)
        run: ls -alh

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found!"
            exit 1
          fi
          npm install

      - name: Run Tests
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found!"
            exit 1
          fi
          npm test

      - name: Build Project
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found!"
            exit 1
          fi
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Deploying to production server..."
          # Add your deployment steps here
